// 假數據生成器

export function generateDummyData() {
  const now = new Date();
  const oneMonthAgo = new Date(now);
  oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);
  
  const oneMonthLater = new Date(now);
  oneMonthLater.setMonth(oneMonthLater.getMonth() + 1);
  
  const sevenDaysLater = new Date(now);
  sevenDaysLater.setDate(sevenDaysLater.getDate() + 7);
  
  const threeDaysAgo = new Date(now);
  threeDaysAgo.setDate(threeDaysAgo.getDate() - 3);

  // 生成假物業數據
  const properties = [
    {
      id: 'prop-1',
      companyId: null,
      propertyNumber: 'A01-P001',
      name: '粉錦公路8號 (租車易)',
      address: '元朗八鄉粉錦公路8號',
      lotNumber: 'DD 111 LOT 1523, 1539, 1541, 1559',
      area: 39840,
      landUse: '露天貯物',
      status: 'HOLDING',
      category: 'GROUP_ASSETS',
      images: [],
      coordinates: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'prop-2',
      companyId: null,
      propertyNumber: 'A01-P002',
      name: '粉錦公路8號 (噴油房)',
      address: '元朗八鄉粉錦公路8號(國際車房)',
      lotNumber: 'DD 111 LOT 1541',
      area: 2095,
      landUse: null,
      status: 'HOLDING',
      category: 'GROUP_ASSETS',
      images: [],
      coordinates: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'prop-3',
      companyId: null,
      propertyNumber: 'A01-P004',
      name: '紅毛潭6號 (維修易)',
      address: '石商粉錦公路6號,紅毛潭',
      lotNumber: 'DD111 LOT 3151, 1524, 1532',
      area: 13022,
      landUse: '露天貯物',
      status: 'HOLDING',
      category: 'GROUP_ASSETS',
      images: [],
      coordinates: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'prop-4',
      companyId: null,
      propertyNumber: 'A01-P005',
      name: '七星崗(四季雅苑側)',
      address: '元朗八鄉七星崗公車站附近',
      lotNumber: 'DD 110 LOT 513',
      area: 4700,
      landUse: '住宅(丙類),休憩用地',
      status: 'HOLDING',
      category: 'GROUP_ASSETS',
      images: [],
      coordinates: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'prop-5',
      companyId: null,
      propertyNumber: 'B01-P001',
      name: '金國場',
      address: '22.439690, 114.092673',
      lotNumber: 'DD111 LOT 2098SBss1, 2098SBss2, 2098SBRP',
      area: 11300,
      landUse: '鄉村式發展',
      status: 'HOLDING',
      category: 'COOPERATIVE_INVESTMENT',
      images: [],
      coordinates: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'prop-6',
      companyId: null,
      propertyNumber: 'A01-P006',
      name: '錦田公路12號',
      address: '元朗錦田公路12號',
      lotNumber: 'DD 111 LOT 2001',
      area: 8500,
      landUse: '商業用途',
      status: 'HOLDING',
      category: 'GROUP_ASSETS',
      images: [],
      coordinates: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'prop-7',
      companyId: null,
      propertyNumber: 'A01-P007',
      name: '八鄉路88號',
      address: '元朗八鄉路88號',
      lotNumber: 'DD 111 LOT 3001',
      area: 12000,
      landUse: '工業用途',
      status: 'HOLDING',
      category: 'GROUP_ASSETS',
      images: [],
      coordinates: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'prop-8',
      companyId: null,
      propertyNumber: 'B01-P002',
      name: '大棠路99號',
      address: '元朗大棠路99號',
      lotNumber: 'DD 111 LOT 4001',
      area: 6500,
      landUse: '住宅用途',
      status: 'HOLDING',
      category: 'COOPERATIVE_INVESTMENT',
      images: [],
      coordinates: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
  ];

  // 生成假租客數據
  const tenants = [
    {
      id: 'tenant-1',
      companyId: null,
      name: '張三',
      email: 'zhang@example.com',
      phone: '12345678',
      idNumber: 'A123456(7)',
      status: 'ACTIVE',
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'tenant-2',
      companyId: null,
      name: '李四',
      email: 'li@example.com',
      phone: '87654321',
      idNumber: 'B234567(8)',
      status: 'ACTIVE',
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'tenant-3',
      companyId: null,
      name: '王五',
      email: 'wang@example.com',
      phone: '11223344',
      idNumber: 'C345678(9)',
      status: 'ACTIVE',
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'tenant-4',
      companyId: null,
      name: '陳六',
      email: 'chen@example.com',
      phone: '22334455',
      idNumber: 'D456789(0)',
      status: 'ACTIVE',
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'tenant-5',
      companyId: null,
      name: '劉七',
      email: 'liu@example.com',
      phone: '33445566',
      idNumber: 'E567890(1)',
      status: 'ACTIVE',
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
  ];

  // 生成假合約數據
  const contracts = [
    {
      id: 'contract-1',
      companyId: null,
      propertyId: 'prop-1',
      tenantId: 'tenant-1',
      startDate: oneMonthAgo.toISOString(),
      endDate: sevenDaysLater.toISOString(), // 即將到期
      rentAmount: 50000,
      deposit: 100000,
      status: 'ACTIVE',
      documentUrl: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'contract-2',
      companyId: null,
      propertyId: 'prop-2',
      tenantId: 'tenant-2',
      startDate: oneMonthAgo.toISOString(),
      endDate: oneMonthLater.toISOString(),
      rentAmount: 30000,
      deposit: 60000,
      status: 'ACTIVE',
      documentUrl: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'contract-3',
      companyId: null,
      propertyId: 'prop-3',
      tenantId: 'tenant-3',
      startDate: oneMonthAgo.toISOString(),
      endDate: oneMonthLater.toISOString(),
      rentAmount: 25000,
      deposit: 50000,
      status: 'ACTIVE',
      documentUrl: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'contract-4',
      companyId: null,
      propertyId: 'prop-4',
      tenantId: 'tenant-4',
      startDate: oneMonthAgo.toISOString(),
      endDate: oneMonthLater.toISOString(),
      rentAmount: 40000,
      deposit: 80000,
      status: 'ACTIVE',
      documentUrl: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'contract-5',
      companyId: null,
      propertyId: 'prop-5',
      tenantId: 'tenant-5',
      startDate: oneMonthAgo.toISOString(),
      endDate: oneMonthLater.toISOString(),
      rentAmount: 35000,
      deposit: 70000,
      status: 'ACTIVE',
      documentUrl: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'contract-6',
      companyId: null,
      propertyId: 'prop-6',
      tenantId: 'tenant-1',
      startDate: oneMonthAgo.toISOString(),
      endDate: oneMonthLater.toISOString(),
      rentAmount: 45000,
      deposit: 90000,
      status: 'ACTIVE',
      documentUrl: null,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
  ];

  // 生成假交易數據
  const transactions = [
    {
      id: 'trans-1',
      companyId: null,
      contractId: 'contract-1',
      type: 'INCOME',
      amount: 50000,
      dueDate: now.toISOString(),
      paidDate: null,
      status: 'PENDING',
      paymentMethod: null,
      description: '租金',
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'trans-2',
      companyId: null,
      contractId: 'contract-2',
      type: 'INCOME',
      amount: 30000,
      dueDate: threeDaysAgo.toISOString(),
      paidDate: null,
      status: 'OVERDUE',
      paymentMethod: null,
      description: '租金',
      createdAt: threeDaysAgo.toISOString(),
      updatedAt: threeDaysAgo.toISOString(),
    },
    {
      id: 'trans-3',
      companyId: null,
      contractId: 'contract-3',
      type: 'INCOME',
      amount: 25000,
      dueDate: oneMonthLater.toISOString(),
      paidDate: null,
      status: 'PENDING',
      paymentMethod: null,
      description: '租金',
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'trans-4',
      companyId: null,
      contractId: 'contract-4',
      type: 'INCOME',
      amount: 40000,
      dueDate: now.toISOString(),
      paidDate: null,
      status: 'PENDING',
      paymentMethod: null,
      description: '租金',
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'trans-5',
      companyId: null,
      contractId: 'contract-5',
      type: 'INCOME',
      amount: 35000,
      dueDate: threeDaysAgo.toISOString(),
      paidDate: null,
      status: 'OVERDUE',
      paymentMethod: null,
      description: '租金',
      createdAt: threeDaysAgo.toISOString(),
      updatedAt: threeDaysAgo.toISOString(),
    },
    {
      id: 'trans-6',
      companyId: null,
      contractId: 'contract-1',
      type: 'EXPENSE',
      amount: 5000,
      dueDate: now.toISOString(),
      paidDate: now.toISOString(),
      status: 'PAID',
      paymentMethod: 'BANK_TRANSFER',
      description: '維修費用',
      createdAt: threeDaysAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'trans-7',
      companyId: null,
      contractId: null,
      type: 'EXPENSE',
      amount: 3000,
      dueDate: now.toISOString(),
      paidDate: now.toISOString(),
      status: 'PAID',
      paymentMethod: 'BANK_TRANSFER',
      description: '管理費',
      createdAt: threeDaysAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'trans-8',
      companyId: null,
      contractId: 'contract-2',
      type: 'EXPENSE',
      amount: 2000,
      dueDate: now.toISOString(),
      paidDate: now.toISOString(),
      status: 'PAID',
      paymentMethod: 'CASH',
      description: '清潔費',
      createdAt: threeDaysAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'trans-9',
      companyId: null,
      contractId: null,
      type: 'EXPENSE',
      amount: 8000,
      dueDate: now.toISOString(),
      paidDate: now.toISOString(),
      status: 'PAID',
      paymentMethod: 'BANK_TRANSFER',
      description: '保險費',
      createdAt: threeDaysAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
  ];

  // 生成假修單數據
  const maintenanceOrders = [
    {
      id: 'maint-1',
      companyId: null,
      propertyId: 'prop-1',
      tenantId: 'tenant-1',
      title: '水龍頭漏水',
      description: '廚房水龍頭持續漏水，需要更換',
      priority: 'HIGH',
      status: 'PENDING',
      assignedTo: null,
      cost: null,
      createdAt: threeDaysAgo.toISOString(),
      updatedAt: threeDaysAgo.toISOString(),
    },
    {
      id: 'maint-2',
      companyId: null,
      propertyId: 'prop-2',
      tenantId: 'tenant-2',
      title: '電燈故障',
      description: '客廳電燈不亮',
      priority: 'MEDIUM',
      status: 'IN_PROGRESS',
      assignedTo: null,
      cost: 800,
      createdAt: threeDaysAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'maint-3',
      companyId: null,
      propertyId: 'prop-3',
      tenantId: 'tenant-3',
      title: '門鎖損壞',
      description: '大門鎖無法正常開啟',
      priority: 'URGENT',
      status: 'PENDING',
      assignedTo: null,
      cost: null,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'maint-4',
      companyId: null,
      propertyId: 'prop-4',
      tenantId: 'tenant-4',
      title: '水管堵塞',
      description: '浴室排水管堵塞',
      priority: 'HIGH',
      status: 'PENDING',
      assignedTo: null,
      cost: null,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'maint-5',
      companyId: null,
      propertyId: 'prop-5',
      tenantId: null,
      title: '外牆粉刷',
      description: '定期外牆維護',
      priority: 'LOW',
      status: 'COMPLETED',
      assignedTo: null,
      cost: 5000,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: threeDaysAgo.toISOString(),
    },
    {
      id: 'maint-6',
      companyId: null,
      propertyId: 'prop-6',
      tenantId: null,
      title: '空調維修',
      description: '空調系統檢查',
      priority: 'MEDIUM',
      status: 'COMPLETED',
      assignedTo: null,
      cost: 3000,
      createdAt: oneMonthAgo.toISOString(),
      updatedAt: threeDaysAgo.toISOString(),
    },
    {
      id: 'maint-7',
      companyId: null,
      propertyId: 'prop-1',
      tenantId: 'tenant-1',
      title: '窗戶損壞',
      description: '臥室窗戶無法關閉',
      priority: 'MEDIUM',
      status: 'PENDING',
      assignedTo: null,
      cost: null,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: 'maint-8',
      companyId: null,
      propertyId: 'prop-7',
      tenantId: null,
      title: '電梯維護',
      description: '定期電梯保養',
      priority: 'MEDIUM',
      status: 'IN_PROGRESS',
      assignedTo: null,
      cost: 12000,
      createdAt: threeDaysAgo.toISOString(),
      updatedAt: now.toISOString(),
    },
  ];

  return {
    properties,
    tenants,
    contracts,
    transactions,
    maintenanceOrders,
  };
}

